#ifndef SERIAL_SUIT_PROTOCOL_H
#define SERIAL_SUIT_PROTOCOL_H

enum RFM_NET_PROTOCOL
{
    RFM_NET_CMD_NOP = 0, /// NOP cmd
    RFM_NET_CMD_SLS,     /// Slave listen enable
    RFM_NET_CMD_SLE,     /// Slave listen disable

    RFM_NET_CMD_STS_HEAD = 10,
    RFM_NET_CMD_LIGHT,
    RFM_NET_CMD_FAN,
    RFM_NET_CMD_SERVO_RAW,
    RFM_NET_CMD_SERVO_SMOOTH,

    RFM_NET_CMD_DEBUG = 40,

    RFM_NET_CMD_FLASH = 50,
    RFM_NET_CMD_FLASH_STOP,
    RFM_NET_CMD_REBOOT,
    RFM_NET_CMD_OFF,
};

enum
{
    SSP_FLASH_OK = 0,
    SSP_FLASH_WRONG_PARAM,
    SSP_FLASH_UNEXIST,
    SSP_FLASH_FAIL,
    SSP_FLASH_WRONG_ADDRESS,
    SSP_FLASH_VERIFY_FAIL,
    SSP_FLASH_WRONG_CRC_ADDRESS,
    SSP_FLASH_WRONG_FULL_LENGTH,
    SSP_FLASH_WRONG_CRC,
};

#endif // SERIAL_SUIT_PROTOCOL_H
